### ISSUE TITLE
Create directory is not exists

### ISSUE THREAD

**Issue by soullivaneuh** [browscap/BrowscapBundle#11]
Actually, if I have this config:

``` yml
browscap:
    cache_dir:            %kernel.root_dir%/shared/%kernel.environment%/browscap
    lowercase:            true
    do_auto_update:       false
```

I have this error on update command:

```
The cache path /[project]/app/shared/dev/browscap is invalid. Are you sure that it exists and that you have permission to access it?
```

It could be useful to create directory if not exists.

Thanks.
